services:
  - type: web
    name: end-to-end-ml-project
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    autoDeploy: true
